apiVersion: apps/v1beta1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: metadata-service-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        application: metadata-service-v1
        version: v1
    spec:
      containers:
      - name: metadata-service-v1
        image: consortit-docker-cme-local.jfrog.io/metadata:image-version
        ports:
        - containerPort: 8080
        - containerPort: 8081
        env:
        - name: dbname
          valueFrom:
            secretKeyRef:
              name: metadata-secret
              key: dbname
        - name: user
          valueFrom:
            secretKeyRef:
              name: metadata-secret
              key: user
        - name: password
          valueFrom:
            secretKeyRef:
              name: metadata-secret
              key: password
        - name: hostname
          valueFrom:
            secretKeyRef:
              name: metadata-secret
              key: hostname
        - name: port
          valueFrom:
            secretKeyRef:
              name: metadata-secret
              key: port
        - name: dbdriver
          valueFrom:
            secretKeyRef:
              name: metadata-secret
              key: dbdriver
        - name: initialData
          valueFrom:
            secretKeyRef:
              name: metadata-secret
              key: initialData
        - name: jwk_kid
          valueFrom:
            secretKeyRef:
              name: metadata-secret
              key: jwk_kid
        - name: jwk_url
          value: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_M4FyC0JPA/.well-known/jwks.json
        - name: jwk_alg
          value: RS256
        - name: appversion
          value: "0.1"
      imagePullSecrets:
        - name: regsecret
---
apiVersion: v1
kind: Service
metadata:
  name: metadata-service-v1
  labels:
    application: metadata-service-v1
    version: v1
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: external
    - port: 81
      protocol: TCP
      targetPort: 8081
      name: external2
  selector:
    application: metadata-service-v1
    version: v1
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: metadata-service-v1
  labels:
    application: metadata-service-v1
    version: v1
spec:
  rules:
  - host: "cme.dev.k8s.consort-it.de"
    http:
      paths:
      - path: /api/v1/metadata-service
        backend:
          serviceName: metadata-service-v1
          servicePort: 80
      - path: /api/v1/metadata-service/health
        backend:
          serviceName: metadata-service-v1
          servicePort: 81
      - path: /api/v1/metadata-service/metrics
        backend:
          serviceName: metadata-service-v1
          servicePort: 81
          
          
          
